export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const AUTH_LOADING = 'AUTH_LOADING';


export const FETCHING_TODOS = 'FETCHING_TODOS';
export const TODOS_SUCCESS = 'TODOS_SUCCESS';
export const TODOS_FAIL = 'TODOS_FAIL';

